name: Regenerate ciphers (manual)

on:
  workflow_dispatch:
    inputs:
      pw:
        description: "Password 3 digit (mis. 123)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate ciphers.js
        env:
          PW: ${{ github.event.inputs.pw }}
        run: |
          if ! [[ "${PW}" =~ ^[0-9]{3}$ ]]; then
            echo "Password harus 3 digit"; exit 1;
          fi
          node tools/encrypt.js

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ciphers.js
          git commit -m "chore: regenerate ciphers (pw=${{ github.event.inputs.pw }})" || echo "No changes"
          git push
